### ISSUE TITLE
Missing trait implementations

### ISSUE THREAD

**Issue by wolfiestyle** [rustonaut/maybe-owned#1]
There is a bunch of missing impl's that would be nice to have for this to become closer to a drop-in replacement for Cow, like `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Display`, `Hash`, `AsRef`, and maybe others.

**Comment by rustonaut** [comment]
Makes sense, I will take a look at it on the weekend.

I guess a feature gate for serde Serialize/Deserialize might belong into
the others category
