### ISSUE TITLE
Other std trait Implementations?

### ISSUE THREAD

**Issue by rustonaut** [rustonaut/maybe-owned#4]
@darkstalker I move the discussion about other traits into a new (this) Issue

On itself I also did though about it recently and I am wondering,
why `std::borrow::Cow` does not have any of such implementations
(at last no general ones, e.g. there is  `Add`/`Assign` for string).

Also for some parts we would have to make sure not to
create a situation which would trigger conflicting trait
implementations (e.g. we cant do something like
`impl<'a, T, F> From<F> for MaybeOwned<'a, T> where T: Into<F>`,
as this could cause problems if there is a T convertable into F,
where people want to write there custom, optimized conversion
to `MaybeOwned<'a, T>`)

I think possible candidates for additional implementations
 would maybe only be some of the trait in `std::ops`

**Comment by rustonaut** [comment]
As well as `AsRef`, `Borrow` and `FromString` 

Different to a general `From` we can have a transitive implementation for `FromString`
as the source type is fixed to `&str`.

**Comment by rustonaut** [comment]
`ToString` should be unnecessary, as it is automatically implemented if `T: Display`.
I'm not even sure if we could implement a custom `ToString` there would be a collision:

1.  `T: Display => MaybeOwned<T>: Display => MaybeOwned<T>: ToString` 
2.  `T: Display => T: ToString => MaybeOwned<T>: ToString`

**Comment by rustonaut** [comment]
I will check / implement `AsRef`, `Borrow` and `FromString` on Friday.

**Comment by wolfiestyle** [comment]
I think a good starting point would be copying the impls from `Cow` where applicable. Some things there aren't the same on `MaybeOwned`, like `Cow<'a, str>` or `Cow<'a, [T]>`. Those are special cases that handle the `ToOwned` conversions, and don't know if it's worth implementing cases like that directly or we should be using a more generic impl like `impl<'a, A> Add<B> for MaybeOwned<'a, T>`. One of the problems doing this is with `Add ` is that we have to handle both by value and by ref dynamically, and the multiple owned vs ref versions. Part of it would look like this:
```Rust
impl<'a, A, B, R> Add<B> for MaybeOwned<'a, A>
    where A: Add<B, Output=R>, &'a A: Add<B, Output=R>
{
    type Output = R;

    fn add(self, rhs: B) -> R {
        match self {
            Owned(o) => o + rhs,
            Borrowed(b) => b + rhs,
        }
    }
}
```
then add all the ref / owned combinations.

**Comment by wolfiestyle** [comment]
sum with itself would be like:
```Rust
impl<'a, 'b, A, B, R> Add<MaybeOwned<'b, B>> for MaybeOwned<'a, A>
    where A: Add<B, Output=R> + Add<&'b B, Output=R>,
        &'a A: Add<B, Output=R> + Add<&'b B, Output=R>
{
    type Output = R;

    fn add(self, rhs: MaybeOwned<'b, B>) -> R {
        match (self, rhs) {
            (Owned(a), Owned(b)) => a + b,
            (Owned(a), Borrowed(b)) => a + b,
            (Borrowed(a), Owned(b)) => a + b,
            (Borrowed(a), Borrowed(b)) => a + b,
        }
    }
}
```
will probably need a macro to copy-paste all this impls programatically.

**Comment by wolfiestyle** [comment]
found some strange error while doing this: https://play.rust-lang.org/?gist=9a0af40152a2d01d29d45e3adfeb9069&version=stable

so maybe it's not a good idea..

**Comment by rustonaut** [comment]
I went through it and some of the thinks can be implemented in a limited form.
Basically most `std::ops` traits can be implemented for:

- combining `MaybeOwned` with `MaybeOwned` producing a `MaybeOwned`
  - e.g. a `MaybeOwned<Bignum>` + `MaybeOwned<Bignum>` => `MaybeOwned<Bignum>`
  - it will always produce a `Owned` variant
  - theoretically the lifetime of it could be any lifetime up to the lifetime of the output 
    type, practically this is currently not possible with rust and you will have to use a
    lifetime which is the overlapping of the left and right hand sides lifetime.
- implement all `*Assing`  operators by first turning the `MaybeOwned` into
  a owned variation and then use `*Assing`  on it

With some forms of specialization which might be implemented in rust it might be
possible to also allow `MaybeOwned` + `MaybeOwned` => `Value` implementations.

**Comment by rustonaut** [comment]
I changed the decision and return the produced value directly instead of
wrapping it in `MaybeOwned` should be more ergonomic.
