### ISSUE TITLE
Serde implementations under feature?

### ISSUE THREAD

**Issue by daboross** [rustonaut/maybe-owned#5]
I'd have a great use case for this if I could store a `MaybeOwned<'a, Data>` in a structure and have it borrowed for serialization, and owned after deserialization.

If you're open to this, I'll write a PR adding serde support under a feature flag. It'd just mean implementing `serde::Serialize` and `serde::Deserialize` implementations for `MaybeOwned` when the inner type is also `Serialize` or `Deserialize` respectively.

**Comment by rustonaut** [comment]
Sure, go ahead.

I hadn't head time to go through the missing corners
of this crate, especially given that I (currently) don't 
need any of this parts myself :wink: So someone 
else contributing to it is pretty nice.

**Comment by rustonaut** [comment]
Oh and please use:

```
[dependencies]
serde = { version="1", optional=true }
```

```
#[cfg(feature="serde")]
```

if possible.

(I didn't know for a long time that optional dependencies can
 be directly used as features, and I'm probably not the only
 one :wink:)

**Comment by daboross** [comment]
Alright, will do it that way- thanks for the quick reply!

I do personally prefer feature names like `serde-1` so that the feature can be kept backwards compatibly if/when serde `2.0.0` is released, but I'll defer to your choice.

**Comment by daboross** [comment]
Opened #6.

**Comment by rustonaut** [comment]
@daboross: Do you want to be listed in `Cargo.toml authors`?

This crate is so small that more or less any contribution can
be seen as a major one, so it would be just reasonable.

**Comment by daboross** [comment]
It doesn't matter too much to me either way - thank you for the offer though! :)

I think it probably makes sense to keep 'authors' as people who regularly maintain the crate.
