### ISSUE TITLE
Implement Clone without T: Clone

### ISSUE THREAD

**Issue by wolfiestyle** [rustonaut/maybe-owned#8]
I noticed that it's possible to implement `Clone` for `MaybeOwned` without requiring `T: Clone` by doing it this way:
```Rust
impl<'a, T> Clone for MaybeOwned<'a, T> {
    fn clone(&self) -> MaybeOwned<'a, T> {
        match *self {
            Owned(ref v) => Borrowed(v),
            Borrowed(v) => Borrowed(v)
        }
    }
}
```

Do you think it's a good idea?

**Comment by rustonaut** [comment]
I don't think it is possible. The `ref` in the match statement has a lifetime based on the `&self` borrow not on `'a`.

For example if you have a `MaybeOwned<'static, T>` then it would have to produce a `&'static T` based on a `&self` of `T` which likely is not `&'static self`.
